name: Build

on:
  workflow_dispatch:

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory tree before build
        run: tree . || true

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Build and Generate .rvp Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: ./gradlew -p patches build generatePatchesFiles --no-daemon --stacktrace --info --scan

      - name: Show directory tree after build
        run: tree . || true

      - name: Upload .rvp artifacts
        uses: actions/upload-artifact@v4
        with:
          name: revanced-patches
          path: patches/build/generated/patches/*.rvp
          
